# Generated by Django 4.1.2 on 2023-01-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SignupApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('pname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TMSBooking',
            fields=[
                ('booking_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('no_of_person', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField()),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookTicketApp.packagedetails')),
                ('tmsuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SignupApp.tmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=200)),
                ('tmsuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SignupApp.tmsuser')),
            ],
        ),
    ]
